// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Cashflow.
    /// </summary>
    public static partial class CashflowExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='company'>
            /// </param>
            public static IList<string> GetBusinessNames(this ICashflow operations, int company)
            {
                return operations.GetBusinessNamesAsync(company).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='company'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<string>> GetBusinessNamesAsync(this ICashflow operations, int company, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetBusinessNamesWithHttpMessagesAsync(company, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='company'>
            /// </param>
            public static IDictionary<string, object> GetVatSummaryList(this ICashflow operations, int company)
            {
                return operations.GetVatSummaryListAsync(company).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='company'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IDictionary<string, object>> GetVatSummaryListAsync(this ICashflow operations, int company, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetVatSummaryListWithHttpMessagesAsync(company, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
