// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Mpt.
    /// </summary>
    public static partial class MptExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            public static IList<TaxDue> GetMptDues(this IMpt operations, int companyId)
            {
                return operations.GetMptDuesAsync(companyId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<TaxDue>> GetMptDuesAsync(this IMpt operations, int companyId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMptDuesWithHttpMessagesAsync(companyId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            public static MonthlyPercentageTaxReturn GetMptPreview(this IMpt operations, int year, int month, int companyId)
            {
                return operations.GetMptPreviewAsync(year, month, companyId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MonthlyPercentageTaxReturn> GetMptPreviewAsync(this IMpt operations, int year, int month, int companyId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetMptPreviewWithHttpMessagesAsync(year, month, companyId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            public static object CreateSubmission(this IMpt operations, int year, int month, int companyId)
            {
                return operations.CreateSubmissionAsync(year, month, companyId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> CreateSubmissionAsync(this IMpt operations, int year, int month, int companyId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateSubmissionWithHttpMessagesAsync(year, month, companyId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
