// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for PaymentForm.
    /// </summary>
    public static partial class PaymentFormExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            public static IList<TaxDue> GetPaymentDues(this IPaymentForm operations, int companyId)
            {
                return operations.GetPaymentDuesAsync(companyId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<TaxDue>> GetPaymentDuesAsync(this IPaymentForm operations, int companyId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetPaymentDuesWithHttpMessagesAsync(companyId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            public static object GetPaymentPreview(this IPaymentForm operations, int year, int month, int companyId, PaymentFormDetails details)
            {
                return operations.GetPaymentPreviewAsync(year, month, companyId, details).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetPaymentPreviewAsync(this IPaymentForm operations, int year, int month, int companyId, PaymentFormDetails details, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetPaymentPreviewWithHttpMessagesAsync(year, month, companyId, details, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            public static object CreateSubmission(this IPaymentForm operations, int year, int month, int companyId, PaymentFormDetails details)
            {
                return operations.CreateSubmissionAsync(year, month, companyId, details).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='month'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> CreateSubmissionAsync(this IPaymentForm operations, int year, int month, int companyId, PaymentFormDetails details, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateSubmissionWithHttpMessagesAsync(year, month, companyId, details, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
