// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for QitGrt.
    /// </summary>
    public static partial class QitGrtExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            public static IList<TaxDue> GetQitGrtDues(this IQitGrt operations, int companyId)
            {
                return operations.GetQitGrtDuesAsync(companyId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<TaxDue>> GetQitGrtDuesAsync(this IQitGrt operations, int companyId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetQitGrtDuesWithHttpMessagesAsync(companyId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='quarter'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            public static object GetQitGrtPreview(this IQitGrt operations, int year, int quarter, int companyId, PriorSubmissionDetails details)
            {
                return operations.GetQitGrtPreviewAsync(year, quarter, companyId, details).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='quarter'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetQitGrtPreviewAsync(this IQitGrt operations, int year, int quarter, int companyId, PriorSubmissionDetails details, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetQitGrtPreviewWithHttpMessagesAsync(year, quarter, companyId, details, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='quarter'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            public static object CreateSubmission(this IQitGrt operations, int year, int quarter, int companyId, PriorSubmissionDetails details)
            {
                return operations.CreateSubmissionAsync(year, quarter, companyId, details).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='quarter'>
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='details'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> CreateSubmissionAsync(this IQitGrt operations, int year, int quarter, int companyId, PriorSubmissionDetails details, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateSubmissionWithHttpMessagesAsync(year, quarter, companyId, details, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
