// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SalesJournal.
    /// </summary>
    public static partial class SalesJournalExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='company'>
            /// </param>
            /// <param name='fromParameter'>
            /// </param>
            /// <param name='to'>
            /// </param>
            public static IList<SalesJournalEntry> GetEntries(this ISalesJournal operations, int company, System.DateTime fromParameter, System.DateTime to)
            {
                return operations.GetEntriesAsync(company, fromParameter, to).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='company'>
            /// </param>
            /// <param name='fromParameter'>
            /// </param>
            /// <param name='to'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<SalesJournalEntry>> GetEntriesAsync(this ISalesJournal operations, int company, System.DateTime fromParameter, System.DateTime to, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetEntriesWithHttpMessagesAsync(company, fromParameter, to, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
