// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for TaxCards.
    /// </summary>
    public static partial class TaxCardsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='form'>
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='period'>
            /// </param>
            public static object MarkAsPaid(this ITaxCards operations, int companyId, string form, int year, int period)
            {
                return operations.MarkAsPaidAsync(companyId, form, year, period).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='companyId'>
            /// </param>
            /// <param name='form'>
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='period'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> MarkAsPaidAsync(this ITaxCards operations, int companyId, string form, int year, int period, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.MarkAsPaidWithHttpMessagesAsync(companyId, form, year, period, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
