// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AnnualRemittanceReturn
    {
        /// <summary>
        /// Initializes a new instance of the AnnualRemittanceReturn class.
        /// </summary>
        public AnnualRemittanceReturn()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AnnualRemittanceReturn class.
        /// </summary>
        public AnnualRemittanceReturn(int? year = default(int?), bool? isAmendment = default(bool?), string withholdAgentCategory = default(string), double? surcharge = default(double?), double? interest = default(double?), double? compromise = default(double?), double? penalties = default(double?), double? taxPayable = default(double?), IList<Transaction1601E> transactions1601E = default(IList<Transaction1601E>), IList<Transaction1606> transactions1606 = default(IList<Transaction1606>), IList<Transaction2304> transactions2304 = default(IList<Transaction2304>), IList<Transaction2307> transactions2307 = default(IList<Transaction2307>), double? totalTaxesWithheld1601E = default(double?), double? totalPenalties1601E = default(double?), double? totalAmountRemitted1601E = default(double?), double? totalTaxesWithheld1606 = default(double?), double? totalPenalties1606 = default(double?), double? totalAmountRemitted1606 = default(double?), double? totalAmountPayable = default(double?), TaxPayer taxPayer = default(TaxPayer), int? daysLate = default(int?))
        {
            Year = year;
            IsAmendment = isAmendment;
            WithholdAgentCategory = withholdAgentCategory;
            Surcharge = surcharge;
            Interest = interest;
            Compromise = compromise;
            Penalties = penalties;
            TaxPayable = taxPayable;
            Transactions1601E = transactions1601E;
            Transactions1606 = transactions1606;
            Transactions2304 = transactions2304;
            Transactions2307 = transactions2307;
            TotalTaxesWithheld1601E = totalTaxesWithheld1601E;
            TotalPenalties1601E = totalPenalties1601E;
            TotalAmountRemitted1601E = totalAmountRemitted1601E;
            TotalTaxesWithheld1606 = totalTaxesWithheld1606;
            TotalPenalties1606 = totalPenalties1606;
            TotalAmountRemitted1606 = totalAmountRemitted1606;
            TotalAmountPayable = totalAmountPayable;
            TaxPayer = taxPayer;
            DaysLate = daysLate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAmendment")]
        public bool? IsAmendment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WithholdAgentCategory")]
        public string WithholdAgentCategory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surcharge")]
        public double? Surcharge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Interest")]
        public double? Interest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Compromise")]
        public double? Compromise { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Penalties")]
        public double? Penalties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayable")]
        public double? TaxPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transactions1601E")]
        public IList<Transaction1601E> Transactions1601E { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transactions1606")]
        public IList<Transaction1606> Transactions1606 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transactions2304")]
        public IList<Transaction2304> Transactions2304 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transactions2307")]
        public IList<Transaction2307> Transactions2307 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalTaxesWithheld1601E")]
        public double? TotalTaxesWithheld1601E { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalPenalties1601E")]
        public double? TotalPenalties1601E { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmountRemitted1601E")]
        public double? TotalAmountRemitted1601E { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalTaxesWithheld1606")]
        public double? TotalTaxesWithheld1606 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalPenalties1606")]
        public double? TotalPenalties1606 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmountRemitted1606")]
        public double? TotalAmountRemitted1606 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmountPayable")]
        public double? TotalAmountPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayer")]
        public TaxPayer TaxPayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DaysLate")]
        public int? DaysLate { get; set; }

    }
}
