// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Company
    {
        /// <summary>
        /// Initializes a new instance of the Company class.
        /// </summary>
        public Company()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Company class.
        /// </summary>
        public Company(int? id = default(int?), string email = default(string), string name = default(string), System.DateTime? birthdate = default(System.DateTime?), string address = default(string), string zipCode = default(string), string contact = default(string), string tIN = default(string), string rDO = default(string), string occupation = default(string), string deductionMethod = default(string), string businessType = default(string), string incomeSource = default(string), string forms = default(string), string cOR = default(string), System.DateTime? dateCreated = default(System.DateTime?), string taxpayerType = default(string), string taxCode = default(string), string signature = default(string), System.DateTime? birRegistration = default(System.DateTime?), string civilStatus = default(string))
        {
            Id = id;
            Email = email;
            Name = name;
            Birthdate = birthdate;
            Address = address;
            ZipCode = zipCode;
            Contact = contact;
            TIN = tIN;
            RDO = rDO;
            Occupation = occupation;
            DeductionMethod = deductionMethod;
            BusinessType = businessType;
            IncomeSource = incomeSource;
            Forms = forms;
            COR = cOR;
            DateCreated = dateCreated;
            TaxpayerType = taxpayerType;
            TaxCode = taxCode;
            Signature = signature;
            BirRegistration = birRegistration;
            CivilStatus = civilStatus;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Birthdate")]
        public System.DateTime? Birthdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZipCode")]
        public string ZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Contact")]
        public string Contact { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TIN")]
        public string TIN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RDO")]
        public string RDO { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Occupation")]
        public string Occupation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeductionMethod")]
        public string DeductionMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BusinessType")]
        public string BusinessType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncomeSource")]
        public string IncomeSource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Forms")]
        public string Forms { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "COR")]
        public string COR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxpayerType")]
        public string TaxpayerType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxCode")]
        public string TaxCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Signature")]
        public string Signature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BirRegistration")]
        public System.DateTime? BirRegistration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CivilStatus")]
        public string CivilStatus { get; set; }

    }
}
