// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Coupon
    {
        /// <summary>
        /// Initializes a new instance of the Coupon class.
        /// </summary>
        public Coupon()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Coupon class.
        /// </summary>
        public Coupon(string code = default(string), string discountType = default(string), string couponType = default(string), double? amount = default(double?), string description = default(string))
        {
            Code = code;
            DiscountType = discountType;
            CouponType = couponType;
            Amount = amount;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DiscountType")]
        public string DiscountType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CouponType")]
        public string CouponType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; private set; }

    }
}
