// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MDDocument
    {
        /// <summary>
        /// Initializes a new instance of the MDDocument class.
        /// </summary>
        public MDDocument()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MDDocument class.
        /// </summary>
        public MDDocument(int? id = default(int?), string user = default(string), int? status = default(int?), string documentType = default(string), IList<MDRequirement> requirements = default(IList<MDRequirement>))
        {
            Id = id;
            User = user;
            Status = status;
            DocumentType = documentType;
            Requirements = requirements;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "User")]
        public string User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public int? Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocumentType")]
        public string DocumentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Requirements")]
        public IList<MDRequirement> Requirements { get; set; }

    }
}
