// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MDRequirement
    {
        /// <summary>
        /// Initializes a new instance of the MDRequirement class.
        /// </summary>
        public MDRequirement()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MDRequirement class.
        /// </summary>
        public MDRequirement(int? id = default(int?), string requirementType = default(string), string link = default(string), int? status = default(int?), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateModified = default(System.DateTime?), System.Guid? uploadedBy = default(System.Guid?))
        {
            Id = id;
            RequirementType = requirementType;
            Link = link;
            Status = status;
            DateCreated = dateCreated;
            DateModified = dateModified;
            UploadedBy = uploadedBy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequirementType")]
        public string RequirementType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Link")]
        public string Link { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public int? Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateModified")]
        public System.DateTime? DateModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UploadedBy")]
        public System.Guid? UploadedBy { get; set; }

    }
}
