// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MonthlyPercentageTaxReturn
    {
        /// <summary>
        /// Initializes a new instance of the MonthlyPercentageTaxReturn class.
        /// </summary>
        public MonthlyPercentageTaxReturn()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MonthlyPercentageTaxReturn class.
        /// </summary>
        public MonthlyPercentageTaxReturn(int? calendarType = default(int?), int? monthEnded = default(int?), int? yearEnded = default(int?), int? month = default(int?), int? year = default(int?), bool? isAmendment = default(bool?), int? attachmentCount = default(int?), IList<TaxableTransaction> taxableTransactions = default(IList<TaxableTransaction>), double? totalTaxDue = default(double?), double? taxWithheld = default(double?), double? previousPayment = default(double?), double? totalTaxCredits = default(double?), double? totalAmountPayable = default(double?), TaxPayer taxPayer = default(TaxPayer), double? taxPayable = default(double?), int? daysLate = default(int?), double? surcharge = default(double?), double? compromise = default(double?), double? interest = default(double?), double? penalties = default(double?))
        {
            CalendarType = calendarType;
            MonthEnded = monthEnded;
            YearEnded = yearEnded;
            Month = month;
            Year = year;
            IsAmendment = isAmendment;
            AttachmentCount = attachmentCount;
            TaxableTransactions = taxableTransactions;
            TotalTaxDue = totalTaxDue;
            TaxWithheld = taxWithheld;
            PreviousPayment = previousPayment;
            TotalTaxCredits = totalTaxCredits;
            TotalAmountPayable = totalAmountPayable;
            TaxPayer = taxPayer;
            TaxPayable = taxPayable;
            DaysLate = daysLate;
            Surcharge = surcharge;
            Compromise = compromise;
            Interest = interest;
            Penalties = penalties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CalendarType")]
        public int? CalendarType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MonthEnded")]
        public int? MonthEnded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "YearEnded")]
        public int? YearEnded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Month")]
        public int? Month { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAmendment")]
        public bool? IsAmendment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AttachmentCount")]
        public int? AttachmentCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxableTransactions")]
        public IList<TaxableTransaction> TaxableTransactions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalTaxDue")]
        public double? TotalTaxDue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxWithheld")]
        public double? TaxWithheld { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PreviousPayment")]
        public double? PreviousPayment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalTaxCredits")]
        public double? TotalTaxCredits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmountPayable")]
        public double? TotalAmountPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayer")]
        public TaxPayer TaxPayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayable")]
        public double? TaxPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DaysLate")]
        public int? DaysLate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surcharge")]
        public double? Surcharge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Compromise")]
        public double? Compromise { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Interest")]
        public double? Interest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Penalties")]
        public double? Penalties { get; set; }

    }
}
