// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MonthlyRemittanceReturn
    {
        /// <summary>
        /// Initializes a new instance of the MonthlyRemittanceReturn class.
        /// </summary>
        public MonthlyRemittanceReturn()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MonthlyRemittanceReturn class.
        /// </summary>
        public MonthlyRemittanceReturn(int? month = default(int?), int? year = default(int?), System.DateTime? dueDate = default(System.DateTime?), bool? isAmendment = default(bool?), bool? hasWithheldTaxes = default(bool?), string aTC = default(string), string taxCodeType = default(string), double? remittanceAmount = default(double?), double? previousRemittance = default(double?), double? netRemittance = default(double?), double? totalAmountPayable = default(double?), TaxPayer taxPayer = default(TaxPayer), double? taxPayable = default(double?), int? daysLate = default(int?), double? surcharge = default(double?), double? compromise = default(double?), double? interest = default(double?), double? penalties = default(double?))
        {
            Month = month;
            Year = year;
            DueDate = dueDate;
            IsAmendment = isAmendment;
            HasWithheldTaxes = hasWithheldTaxes;
            ATC = aTC;
            TaxCodeType = taxCodeType;
            RemittanceAmount = remittanceAmount;
            PreviousRemittance = previousRemittance;
            NetRemittance = netRemittance;
            TotalAmountPayable = totalAmountPayable;
            TaxPayer = taxPayer;
            TaxPayable = taxPayable;
            DaysLate = daysLate;
            Surcharge = surcharge;
            Compromise = compromise;
            Interest = interest;
            Penalties = penalties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Month")]
        public int? Month { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DueDate")]
        public System.DateTime? DueDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAmendment")]
        public bool? IsAmendment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HasWithheldTaxes")]
        public bool? HasWithheldTaxes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ATC")]
        public string ATC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxCodeType")]
        public string TaxCodeType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RemittanceAmount")]
        public double? RemittanceAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PreviousRemittance")]
        public double? PreviousRemittance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NetRemittance")]
        public double? NetRemittance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmountPayable")]
        public double? TotalAmountPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayer")]
        public TaxPayer TaxPayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayable")]
        public double? TaxPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DaysLate")]
        public int? DaysLate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surcharge")]
        public double? Surcharge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Compromise")]
        public double? Compromise { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Interest")]
        public double? Interest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Penalties")]
        public double? Penalties { get; set; }

    }
}
