// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PriorSubmissionDetails
    {
        /// <summary>
        /// Initializes a new instance of the PriorSubmissionDetails class.
        /// </summary>
        public PriorSubmissionDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PriorSubmissionDetails class.
        /// </summary>
        public PriorSubmissionDetails(double? excessCredits = default(double?), double? taxableIncome = default(double?), double? taxPayment = default(double?), double? taxWithheld = default(double?), string requiredFields = default(string))
        {
            ExcessCredits = excessCredits;
            TaxableIncome = taxableIncome;
            TaxPayment = taxPayment;
            TaxWithheld = taxWithheld;
            RequiredFields = requiredFields;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExcessCredits")]
        public double? ExcessCredits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxableIncome")]
        public double? TaxableIncome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayment")]
        public double? TaxPayment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxWithheld")]
        public double? TaxWithheld { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequiredFields")]
        public string RequiredFields { get; set; }

    }
}
