// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PurchaseCapitalGoodsNotExceedComputation
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PurchaseCapitalGoodsNotExceedComputation class.
        /// </summary>
        public PurchaseCapitalGoodsNotExceedComputation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PurchaseCapitalGoodsNotExceedComputation class.
        /// </summary>
        public PurchaseCapitalGoodsNotExceedComputation(System.DateTime? datePurchased = default(System.DateTime?), string description = default(string), double? amount = default(double?), double? inputTax = default(double?))
        {
            DatePurchased = datePurchased;
            Description = description;
            Amount = amount;
            InputTax = inputTax;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DatePurchased")]
        public System.DateTime? DatePurchased { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InputTax")]
        public double? InputTax { get; private set; }

    }
}
