// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QuarterlyIncomeTaxReturn
    {
        /// <summary>
        /// Initializes a new instance of the QuarterlyIncomeTaxReturn class.
        /// </summary>
        public QuarterlyIncomeTaxReturn()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QuarterlyIncomeTaxReturn class.
        /// </summary>
        public QuarterlyIncomeTaxReturn(int? year = default(int?), int? quarter = default(int?), bool? isAmendment = default(bool?), int? attachmentCount = default(int?), double? revenue = default(double?), double? partnershipRevenue = default(double?), double? totalRevenue = default(double?), double? operationalCost = default(double?), double? grossIncomeFromOperation = default(double?), double? otherIncome = default(double?), double? totalGrossIncome = default(double?), double? deductions = default(double?), double? taxableIncome = default(double?), double? taxableIncomePreviousQuarter = default(double?), double? taxableIncomeToDate = default(double?), double? taxDue = default(double?), double? priorYearExcessCredits = default(double?), double? taxPaymentsPreviousQuarters = default(double?), double? taxWithheldPreviousQuarters = default(double?), double? taxWithheld = default(double?), double? previousPayment = default(double?), double? otherPayments = default(double?), double? totalCredits = default(double?), double? totalAmountPayable = default(double?), double? aggregateAmountPayable = default(double?), TaxPayer taxPayer = default(TaxPayer), double? taxPayable = default(double?), int? daysLate = default(int?), double? surcharge = default(double?), double? compromise = default(double?), double? interest = default(double?), double? penalties = default(double?))
        {
            Year = year;
            Quarter = quarter;
            IsAmendment = isAmendment;
            AttachmentCount = attachmentCount;
            Revenue = revenue;
            PartnershipRevenue = partnershipRevenue;
            TotalRevenue = totalRevenue;
            OperationalCost = operationalCost;
            GrossIncomeFromOperation = grossIncomeFromOperation;
            OtherIncome = otherIncome;
            TotalGrossIncome = totalGrossIncome;
            Deductions = deductions;
            TaxableIncome = taxableIncome;
            TaxableIncomePreviousQuarter = taxableIncomePreviousQuarter;
            TaxableIncomeToDate = taxableIncomeToDate;
            TaxDue = taxDue;
            PriorYearExcessCredits = priorYearExcessCredits;
            TaxPaymentsPreviousQuarters = taxPaymentsPreviousQuarters;
            TaxWithheldPreviousQuarters = taxWithheldPreviousQuarters;
            TaxWithheld = taxWithheld;
            PreviousPayment = previousPayment;
            OtherPayments = otherPayments;
            TotalCredits = totalCredits;
            TotalAmountPayable = totalAmountPayable;
            AggregateAmountPayable = aggregateAmountPayable;
            TaxPayer = taxPayer;
            TaxPayable = taxPayable;
            DaysLate = daysLate;
            Surcharge = surcharge;
            Compromise = compromise;
            Interest = interest;
            Penalties = penalties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quarter")]
        public int? Quarter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAmendment")]
        public bool? IsAmendment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AttachmentCount")]
        public int? AttachmentCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Revenue")]
        public double? Revenue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnershipRevenue")]
        public double? PartnershipRevenue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalRevenue")]
        public double? TotalRevenue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationalCost")]
        public double? OperationalCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GrossIncomeFromOperation")]
        public double? GrossIncomeFromOperation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OtherIncome")]
        public double? OtherIncome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalGrossIncome")]
        public double? TotalGrossIncome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Deductions")]
        public double? Deductions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxableIncome")]
        public double? TaxableIncome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxableIncomePreviousQuarter")]
        public double? TaxableIncomePreviousQuarter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxableIncomeToDate")]
        public double? TaxableIncomeToDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxDue")]
        public double? TaxDue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PriorYearExcessCredits")]
        public double? PriorYearExcessCredits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPaymentsPreviousQuarters")]
        public double? TaxPaymentsPreviousQuarters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxWithheldPreviousQuarters")]
        public double? TaxWithheldPreviousQuarters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxWithheld")]
        public double? TaxWithheld { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PreviousPayment")]
        public double? PreviousPayment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OtherPayments")]
        public double? OtherPayments { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalCredits")]
        public double? TotalCredits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmountPayable")]
        public double? TotalAmountPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AggregateAmountPayable")]
        public double? AggregateAmountPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayer")]
        public TaxPayer TaxPayer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayable")]
        public double? TaxPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DaysLate")]
        public int? DaysLate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surcharge")]
        public double? Surcharge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Compromise")]
        public double? Compromise { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Interest")]
        public double? Interest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Penalties")]
        public double? Penalties { get; set; }

    }
}
