// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Remittance1601EModel
    {
        /// <summary>
        /// Initializes a new instance of the Remittance1601EModel class.
        /// </summary>
        public Remittance1601EModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Remittance1601EModel class.
        /// </summary>
        public Remittance1601EModel(System.DateTime? date = default(System.DateTime?), int? period = default(int?), int? year = default(int?), int? company = default(int?), string bank = default(string), double? taxesWithheld = default(double?), double? penalties = default(double?), double? totalAmountRemitted = default(double?))
        {
            Date = date;
            Period = period;
            Year = year;
            Company = company;
            Bank = bank;
            TaxesWithheld = taxesWithheld;
            Penalties = penalties;
            TotalAmountRemitted = totalAmountRemitted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Period")]
        public int? Period { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Company")]
        public int? Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bank")]
        public string Bank { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxesWithheld")]
        public double? TaxesWithheld { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Penalties")]
        public double? Penalties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmountRemitted")]
        public double? TotalAmountRemitted { get; set; }

    }
}
