// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Remittance2304Model
    {
        /// <summary>
        /// Initializes a new instance of the Remittance2304Model class.
        /// </summary>
        public Remittance2304Model()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Remittance2304Model class.
        /// </summary>
        public Remittance2304Model(int? company = default(int?), string tIN = default(string), string name = default(string), string aTC = default(string), string incomeNature = default(string), double? incomeAmount = default(double?))
        {
            Company = company;
            TIN = tIN;
            Name = name;
            ATC = aTC;
            IncomeNature = incomeNature;
            IncomeAmount = incomeAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Company")]
        public int? Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TIN")]
        public string TIN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ATC")]
        public string ATC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncomeNature")]
        public string IncomeNature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncomeAmount")]
        public double? IncomeAmount { get; set; }

    }
}
