// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RemittanceCollection
    {
        /// <summary>
        /// Initializes a new instance of the RemittanceCollection class.
        /// </summary>
        public RemittanceCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RemittanceCollection class.
        /// </summary>
        public RemittanceCollection(IList<Remittance1601EModel> remittance1601EModel = default(IList<Remittance1601EModel>), IList<Remittance1606Model> remittance1606Model = default(IList<Remittance1606Model>), IList<Remittance2304Model> remittance2304Model = default(IList<Remittance2304Model>), IList<Remittance2307Model> remittance2307Model = default(IList<Remittance2307Model>))
        {
            Remittance1601EModel = remittance1601EModel;
            Remittance1606Model = remittance1606Model;
            Remittance2304Model = remittance2304Model;
            Remittance2307Model = remittance2307Model;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remittance1601EModel")]
        public IList<Remittance1601EModel> Remittance1601EModel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remittance1606Model")]
        public IList<Remittance1606Model> Remittance1606Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remittance2304Model")]
        public IList<Remittance2304Model> Remittance2304Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remittance2307Model")]
        public IList<Remittance2307Model> Remittance2307Model { get; set; }

    }
}
