// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SalesJournalEntry
    {
        /// <summary>
        /// Initializes a new instance of the SalesJournalEntry class.
        /// </summary>
        public SalesJournalEntry()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SalesJournalEntry class.
        /// </summary>
        public SalesJournalEntry(System.DateTime? date = default(System.DateTime?), string particulars = default(string), string controlNo = default(string), string tIN = default(string), double? vatExemptSale = default(double?), double? vatableSale = default(double?), double? zeroRatedSale = default(double?), double? outputTax = default(double?), double? totalAmount = default(double?), string salesClassification = default(string), double? classificationValue = default(double?))
        {
            Date = date;
            Particulars = particulars;
            ControlNo = controlNo;
            TIN = tIN;
            VatExemptSale = vatExemptSale;
            VatableSale = vatableSale;
            ZeroRatedSale = zeroRatedSale;
            OutputTax = outputTax;
            TotalAmount = totalAmount;
            SalesClassification = salesClassification;
            ClassificationValue = classificationValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Particulars")]
        public string Particulars { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ControlNo")]
        public string ControlNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TIN")]
        public string TIN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VatExemptSale")]
        public double? VatExemptSale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VatableSale")]
        public double? VatableSale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZeroRatedSale")]
        public double? ZeroRatedSale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OutputTax")]
        public double? OutputTax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAmount")]
        public double? TotalAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SalesClassification")]
        public string SalesClassification { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClassificationValue")]
        public double? ClassificationValue { get; set; }

    }
}
