// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Settlement
    {
        /// <summary>
        /// Initializes a new instance of the Settlement class.
        /// </summary>
        public Settlement()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Settlement class.
        /// </summary>
        public Settlement(int? id = default(int?), System.DateTime? dateCreated = default(System.DateTime?), string channel = default(string), string reference = default(string), double? amount = default(double?))
        {
            Id = id;
            DateCreated = dateCreated;
            Channel = channel;
            Reference = reference;
            Amount = amount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Channel")]
        public string Channel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Reference")]
        public string Reference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

    }
}
