// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TaxPayer
    {
        /// <summary>
        /// Initializes a new instance of the TaxPayer class.
        /// </summary>
        public TaxPayer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaxPayer class.
        /// </summary>
        public TaxPayer(string tIN = default(string), string rDO = default(string), string occupation = default(string), int? filerType = default(int?), int? incomeTaxCode = default(int?), string filerName = default(string), string tradeName = default(string), string address = default(string), string zipCode = default(string), System.DateTime? birthdate = default(System.DateTime?), string contact = default(string), string email = default(string), string citizenship = default(string), string foreignTaxNumber = default(string), bool? claimingForeignTaxCredits = default(bool?), int? incomeTaxRateType = default(int?), int? deductionMethod = default(int?), object signature = default(object), bool? availingTaxRelief = default(bool?), string taxRelief = default(string), System.DateTime? birRegistration = default(System.DateTime?), string civilStatus = default(string), bool? spouseHasIncome = default(bool?))
        {
            TIN = tIN;
            RDO = rDO;
            Occupation = occupation;
            FilerType = filerType;
            IncomeTaxCode = incomeTaxCode;
            FilerName = filerName;
            TradeName = tradeName;
            Address = address;
            ZipCode = zipCode;
            Birthdate = birthdate;
            Contact = contact;
            Email = email;
            Citizenship = citizenship;
            ForeignTaxNumber = foreignTaxNumber;
            ClaimingForeignTaxCredits = claimingForeignTaxCredits;
            IncomeTaxRateType = incomeTaxRateType;
            DeductionMethod = deductionMethod;
            Signature = signature;
            AvailingTaxRelief = availingTaxRelief;
            TaxRelief = taxRelief;
            BirRegistration = birRegistration;
            CivilStatus = civilStatus;
            SpouseHasIncome = spouseHasIncome;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TIN")]
        public string TIN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RDO")]
        public string RDO { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Occupation")]
        public string Occupation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FilerType")]
        public int? FilerType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncomeTaxCode")]
        public int? IncomeTaxCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FilerName")]
        public string FilerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TradeName")]
        public string TradeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZipCode")]
        public string ZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Birthdate")]
        public System.DateTime? Birthdate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Contact")]
        public string Contact { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Citizenship")]
        public string Citizenship { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ForeignTaxNumber")]
        public string ForeignTaxNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClaimingForeignTaxCredits")]
        public bool? ClaimingForeignTaxCredits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncomeTaxRateType")]
        public int? IncomeTaxRateType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeductionMethod")]
        public int? DeductionMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Signature")]
        public object Signature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AvailingTaxRelief")]
        public bool? AvailingTaxRelief { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxRelief")]
        public string TaxRelief { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BirRegistration")]
        public System.DateTime? BirRegistration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CivilStatus")]
        public string CivilStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SpouseHasIncome")]
        public bool? SpouseHasIncome { get; set; }

    }
}
