// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TaxSubmission
    {
        /// <summary>
        /// Initializes a new instance of the TaxSubmission class.
        /// </summary>
        public TaxSubmission()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaxSubmission class.
        /// </summary>
        public TaxSubmission(int? id = default(int?), int? company = default(int?), int? year = default(int?), int? period = default(int?), string formType = default(string), string formLink = default(string), double? taxPayable = default(double?), double? penalties = default(double?), double? totalPayable = default(double?), string status = default(string), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateExpired = default(System.DateTime?), TaxSettlement taxSettlement = default(TaxSettlement), string confirmation = default(string), string record = default(string), string name = default(string), string gCashReference = default(string), double? taxWithheld = default(double?), int? payment = default(int?))
        {
            Id = id;
            Company = company;
            Year = year;
            Period = period;
            FormType = formType;
            FormLink = formLink;
            TaxPayable = taxPayable;
            Penalties = penalties;
            TotalPayable = totalPayable;
            Status = status;
            DateCreated = dateCreated;
            DateExpired = dateExpired;
            TaxSettlement = taxSettlement;
            Confirmation = confirmation;
            Record = record;
            Name = name;
            GCashReference = gCashReference;
            TaxWithheld = taxWithheld;
            Payment = payment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Company")]
        public int? Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Period")]
        public int? Period { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FormType")]
        public string FormType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FormLink")]
        public string FormLink { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxPayable")]
        public double? TaxPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Penalties")]
        public double? Penalties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalPayable")]
        public double? TotalPayable { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateExpired")]
        public System.DateTime? DateExpired { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxSettlement")]
        public TaxSettlement TaxSettlement { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Confirmation")]
        public string Confirmation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Record")]
        public string Record { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GCashReference")]
        public string GCashReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxWithheld")]
        public double? TaxWithheld { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Payment")]
        public int? Payment { get; set; }

    }
}
