// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class VatableSalesComputation
    {
        /// <summary>
        /// Initializes a new instance of the VatableSalesComputation class.
        /// </summary>
        public VatableSalesComputation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VatableSalesComputation class.
        /// </summary>
        public VatableSalesComputation(double? amountSalesForThePeriod = default(double?), string atc = default(string), string industriesCoveredByVAT = default(string), double? outputTax = default(double?))
        {
            AmountSalesForThePeriod = amountSalesForThePeriod;
            Atc = atc;
            IndustriesCoveredByVAT = industriesCoveredByVAT;
            OutputTax = outputTax;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AmountSalesForThePeriod")]
        public double? AmountSalesForThePeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Atc")]
        public string Atc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IndustriesCoveredByVAT")]
        public string IndustriesCoveredByVAT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OutputTax")]
        public double? OutputTax { get; set; }

    }
}
