// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TaxumoChatBot.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WithheldTax
    {
        /// <summary>
        /// Initializes a new instance of the WithheldTax class.
        /// </summary>
        public WithheldTax()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WithheldTax class.
        /// </summary>
        public WithheldTax(int? id = default(int?), int? company = default(int?), int? year = default(int?), int? quarter = default(int?), double? amount = default(double?), string file = default(string), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateModified = default(System.DateTime?), string businessTIN = default(string), string businessName = default(string), double? firstMonthIncome = default(double?), double? secondMonthIncome = default(double?), double? thirdMonthIncome = default(double?), string taxCode = default(string), string type = default(string))
        {
            Id = id;
            Company = company;
            Year = year;
            Quarter = quarter;
            Amount = amount;
            File = file;
            DateCreated = dateCreated;
            DateModified = dateModified;
            BusinessTIN = businessTIN;
            BusinessName = businessName;
            FirstMonthIncome = firstMonthIncome;
            SecondMonthIncome = secondMonthIncome;
            ThirdMonthIncome = thirdMonthIncome;
            TaxCode = taxCode;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Company")]
        public int? Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quarter")]
        public int? Quarter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "File")]
        public string File { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateModified")]
        public System.DateTime? DateModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BusinessTIN")]
        public string BusinessTIN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BusinessName")]
        public string BusinessName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstMonthIncome")]
        public double? FirstMonthIncome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecondMonthIncome")]
        public double? SecondMonthIncome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ThirdMonthIncome")]
        public double? ThirdMonthIncome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxCode")]
        public string TaxCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

    }
}
